import SpotifyWebApi from "spotify-web-api-node";

const SPOTIFY_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID;
const SPOTIFY_CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET;
const SPOTIFY_REDIRECT_URI = process.env.SPOTIFY_REDIRECT_URI || "http://localhost:3000/api/spotify/callback";

function createSpotifyClient(accessToken?: string): SpotifyWebApi {
  const client = new SpotifyWebApi({
    clientId: SPOTIFY_CLIENT_ID,
    clientSecret: SPOTIFY_CLIENT_SECRET,
    redirectUri: SPOTIFY_REDIRECT_URI,
  });
  if (accessToken) {
    client.setAccessToken(accessToken);
  }
  return client;
}

export function getAuthUrl(userId: string): string {
  const scopes = ["playlist-modify-public", "playlist-modify-private", "user-read-private", "user-read-email"];
  const client = createSpotifyClient();
  return client.createAuthorizeURL(scopes, userId);
}

export async function exchangeCodeForToken(code: string): Promise<{
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}> {
  const client = createSpotifyClient();
  const data = await client.authorizationCodeGrant(code);
  return {
    accessToken: data.body.access_token,
    refreshToken: data.body.refresh_token,
    expiresIn: data.body.expires_in,
  };
}

export async function refreshAccessToken(refreshToken: string): Promise<{
  accessToken: string;
  expiresIn: number;
  refreshToken?: string;
}> {
  const client = createSpotifyClient();
  client.setRefreshToken(refreshToken);
  const data = await client.refreshAccessToken();
  return {
    accessToken: data.body.access_token,
    expiresIn: data.body.expires_in,
    refreshToken: data.body.refresh_token || undefined,
  };
}

export async function getSpotifyUserProfile(accessToken: string): Promise<SpotifyApi.UserProfileResponse> {
  const client = createSpotifyClient(accessToken);
  const data = await client.getMe();
  return data.body;
}

export async function createPlaylist(
  accessToken: string,
  playlistName: string,
  description: string = ""
): Promise<any> {
  const client = createSpotifyClient(accessToken);
  const data = await client.createPlaylist(playlistName, {
    description,
    public: false,
  });
  return data.body;
}

export async function searchTracks(
  accessToken: string,
  query: string,
  limit: number = 1
): Promise<SpotifyApi.TrackObjectFull[]> {
  const client = createSpotifyClient(accessToken);
  const data = await client.searchTracks(query, { limit });
  return data.body.tracks?.items || [];
}

export async function addTracksToPlaylist(
  accessToken: string,
  playlistId: string,
  uris: string[]
): Promise<void> {
  const client = createSpotifyClient(accessToken);
  // Spotify allows max 100 tracks per request
  for (let i = 0; i < uris.length; i += 100) {
    const chunk = uris.slice(i, i + 100);
    await client.addTracksToPlaylist(playlistId, chunk);
  }
}

export async function searchTrackUris(
  accessToken: string,
  songQueries: string[]
): Promise<string[]> {
  const uris: string[] = [];
  for (const query of songQueries) {
    const tracks = await searchTracks(accessToken, query);
    if (tracks.length > 0) {
      uris.push(tracks[0].uri);
    }
  }
  return uris;
}

export async function createPartyPlaylist(
  accessToken: string,
  eventName: string,
  eventType: string,
  songList: string[]
): Promise<string> {
  // Step 1: Create playlist
  const playlist = await createPlaylist(
    accessToken,
    `${eventName} Playlist`,
    `Music for ${eventName} - a ${eventType} generated by PartyPilot`
  );
  
  // Step 2: Search for tracks
  const trackUris = await searchTrackUris(accessToken, songList);
  
  // Step 3: Add tracks to playlist
  if (trackUris.length > 0) {
    await addTracksToPlaylist(accessToken, playlist.id, trackUris);
  }
  
  return playlist.external_urls.spotify;
}
